### ISSUE TITLE
Subdirectory for theme files

### ISSUE THREAD

**Issue by szepeviktor** [45-North-Ventures-LLC/jackpine#9]
@dltanner While this project is very young
please consider stuffing all WordPress files in /theme as https://github.com/timber/starter-theme does.

**Comment by drdogbot7** [comment]
Wait... you can do this now? 🤯

**Comment by szepeviktor** [comment]
WordPress core supports it 5 lightyears ago!

**Comment by dltanner** [comment]
This is a great idea. It'll clean up the file structure a lot. Working on the refactoring...

**Comment by aedontanner** [comment]
This change has been implemented on the `next` branch.
